
sudo: required
language: ruby
branches:
  only:
  - master

services:
  - docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- sudo  bash prepare.sh
script:
- sudo  bash sync.sh
