
language: ruby

services:
  - docker
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- bash imdingtalk/gcrsync/prepare.sh
script:
- bash imdingtalk/gcrsync/sync.sh
